### ISSUE TITLE
Please add fullscreen shortcut (F)

### ISSUE THREAD

**Issue by CHJ85** [rafalb8/HBOMaxKeyboard#1]
Hi there. Could you please add fullscreen shortcut (F)?
And also add max.com now that it's no longer hbomax.com in the US.
Thanks.

**Comment by rafalb8** [comment]
Added in ab6f179

**Comment by CHJ85** [comment]
Thank you!

**Comment by CHJ85** [comment]
There are some issues with the script now.
Only the fullscreen function work and pause/play with spacebar works once I highlight the player with a mouse click.
I'm working on a fix now. I'll PR it to you.

**Comment by CHJ85** [comment]
Okay I submitted an updated version https://github.com/rafalb8/HBOMaxKeyboard/pull/2 . The script works as it should now.
